# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.winrm.transport = "plaintext"
  config.winrm.basic_auth_only = true

  config.vm.define "windows_server" do |ws|
    ws.vm.box = "jborean93/WindowsServer2019"
    ws.vm.hostname = "windowsserver"
    ws.vm.boot_timeout = 20
    ws.vm.network "private_network", ip: "192.168.1.10", netmask: "255.255.255.0"

    ws.vm.network "forwarded_port", guest: 3389, host: 3391, auto_correct: true

    ws.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = 2
    end
  end

  config.vm.define "windows_user" do |wuser|
    wuser.vm.box = "inclusivedesign/windows10-eval"
    wuser.vm.hostname = "windows10"
    wuser.vm.network "private_network", ip: "192.168.1.11", netmask: "255.255.255.0"
    wuser.vm.communicator = "winrm"
    wuser.vm.boot_timeout = 20
    wuser.vm.network "forwarded_port", guest: 3389, host: 3392, auto_correct: true

    wuser.vm.provider "virtualbox" do |vb|
      vb.memory = "6144"
      vb.cpus = 2
    end
  end
end
